language: php

php:
  - 7.1

install:
  - composer validate --no-check-all --ansi
  - composer install --prefer-dist --no-interaction --optimize-autoloader
  
script:
  - sh -c "~/.composer/vendor/bin/phpcs web;"
